/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Attendence;

import java.text.SimpleDateFormat;
import java.util.Date;
import student_management_system.DBConnect;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class AttendenceTrack extends javax.swing.JFrame {
    int pr = 0,ab = 0;
    String date1,date2,date3,defaultDate;
    
    public AttendenceTrack() {
        initComponents();
        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String fd = sdf.format(today);
        defaultDate = fd;
        int sno = 1;
        try{
            Connection con = DBConnect.connect();
            PreparedStatement ps = con.prepareStatement("select s1.rollno,s1.name,a1.pa from student s1 join attendence a1 on s1.rollno = a1.rollno");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                System.out.println("hi");
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
                String absent = "";
                if (present.equalsIgnoreCase("-")){
                    ab++;
                    absent = "-";
                }
                if (present.equalsIgnoreCase("absent")){
                    ab++;
                    absent = "absent";
                }
                else
                    pr++;
                String sno1 = String.valueOf(sno);
                String tbData[] = {sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model = (DefaultTableModel)tbl.getModel();
                tb1Model.addRow(tbData);
                sno++;
        }
        p.setText(String.valueOf(pr));
        a.setText(String.valueOf(ab));
        pr=ab=0;
        }catch (Exception e){}   
    }
    public void clearTable(JTable table){
        DefaultTableModel model = (DefaultTableModel)table.getModel();
           model.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        search_cb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        submit_btn1 = new javax.swing.JButton();
        submit_btn2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();
        go_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        search_btn2 = new javax.swing.JButton();
        search_txt = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 89, 255));

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 740, 310));

        search_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cbActionPerformed(evt);
            }
        });
        jPanel2.add(search_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 270, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SEARCH BY ROLL NUMBER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        submit_btn.setBackground(new java.awt.Color(102, 153, 255));
        submit_btn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("ADD");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        submit_btn1.setBackground(new java.awt.Color(102, 153, 255));
        submit_btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        submit_btn1.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn1.setText("SUBMIT");
        submit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(submit_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        submit_btn2.setBackground(new java.awt.Color(102, 153, 255));
        submit_btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        submit_btn2.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn2.setText("BACK");
        submit_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(submit_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("ATTENDENCE TRACK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("FROM :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("TO :");

        go_btn.setBackground(new java.awt.Color(102, 153, 255));
        go_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        go_btn.setForeground(new java.awt.Color(255, 255, 255));
        go_btn.setText("GO");
        go_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("ABSENT :");

        p.setBackground(new java.awt.Color(0, 255, 0));
        p.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        p.setForeground(new java.awt.Color(51, 255, 0));
        p.setText("--------");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("SEARCH :");

        search_btn.setBackground(new java.awt.Color(102, 153, 255));
        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("SEARCH");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 255, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setText("PRESENT :");

        a.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        a.setForeground(new java.awt.Color(255, 51, 51));
        a.setText("  --------");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "ROLL NUMBER", "NAME", "PRESENT", "ABSENT"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        search_btn2.setBackground(new java.awt.Color(102, 153, 255));
        search_btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search_btn2.setForeground(new java.awt.Color(255, 255, 255));
        search_btn2.setText("BACK");
        search_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn2ActionPerformed(evt);
            }
        });

        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(search_btn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9)
                                .addGap(284, 284, 284)
                                .addComponent(go_btn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p)
                                .addGap(224, 224, 224)
                                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(search_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(a)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(go_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_cbActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        try{
            clearTable(tbl);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date1=(d1.getDate() != null) ? sdf.format(d1.getDate()):defaultDate;
            date2=(d2.getDate() != null) ? sdf.format(d2.getDate()):defaultDate;
            int sno = 1;
            Connection con = DBConnect.connect();
            PreparedStatement ps = con.prepareStatement("select s1.rollno,s1.name,a1.pa from student s1 join attendence a1 on s1.rollno where a1.rollno =?");
            ps.setString(1,date1);
            ps.setString(2,date2);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
                String absent = "";
                if (present.equalsIgnoreCase("-")){
                    ab++;
                    absent = "-";
                }
                if (present.equalsIgnoreCase("absent")){
                    ab++;
                    absent = "absent";
                }
                else
                    pr++;
                String sno1 = String.valueOf(sno);
                String tbData[] = {sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model = (DefaultTableModel)tbl.getModel();
                tb1Model.addRow(tbData);
                sno++;
        }
        p.setText(String.valueOf(pr));
        a.setText(String.valueOf(ab));
        pr=ab=0;
        }catch (Exception e){}   
    
    }//GEN-LAST:event_submit_btnActionPerformed

    private void submit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_btn1ActionPerformed

    private void submit_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_btn2ActionPerformed

    private void go_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_btnActionPerformed
        // TODO add your handling code here:
        try{
            clearTable(tbl);
            int sno = 1;
            Connection con = DBConnect.connect();
            PreparedStatement ps = con.prepareStatement("select s1.rollno,s1.name,a1.pa from student s1 join attendence a1 on s1.rollno = a1.rollno where a1.rollno = ?");
            ps.setString(1,search_txt.getText());
            ResultSet rs = ps.executeQuery();
            int count =0;
            while(rs.next()){
                count++;
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
                String absent = "";
//                if (!present.equalsIgnoreCase("-")){
//                    ab++;
//                    absent = "-";
//                }
                if (!present.equalsIgnoreCase("present")){
                    ab++;
                    absent = "absent";
                }
                else
                    pr++;
                String sno1 = String.valueOf(sno);
                String tbData[] = {sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model = (DefaultTableModel)tbl.getModel();
                tb1Model.addRow(tbData);
                sno++;
        }
        if (count==0)
            JOptionPane.showMessageDialog(null,"No such roll number found");
        p.setText(String.valueOf(pr));
        a.setText(String.valueOf(ab));
        pr=ab=0;
        }catch (Exception e){}   
    
       

    }//GEN-LAST:event_go_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void search_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_search_btn2ActionPerformed

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendenceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendenceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendenceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendenceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendenceTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JButton go_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel p;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton search_btn2;
    private javax.swing.JComboBox<String> search_cb;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JButton submit_btn1;
    private javax.swing.JButton submit_btn2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
