/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fee;
import student_management_system.DBConnect;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class StudentFee extends javax.swing.JFrame {
    String totalAmt ;
    String rollno;
    int changePendFee=0;
    int flag = 0;

    /**
     * Creates new form StudentFee
     */
    public StudentFee() {
        initComponents();
        try{
            Connection con = DBConnect.connect();
        
            PreparedStatement p1 = con.prepareStatement("select * from student");
            ResultSet rs = p1.executeQuery();
            while(rs.next()){
                roll_txt.addItem(rs.getString("rollno"));
            }
        }catch(Exception e){}
    }
    
    public void fetchStud(){
        roll_txt.removeAllItems();
        try {
        Connection con = DBConnect.connect();
//        to fetch all the roll numbers
        PreparedStatement ps = con.prepareStatement("select * from student");
        ResultSet rs = ps.executeQuery();
//        to fetch all the students who had submitted their full fee
        PreparedStatement ps2 = con.prepareStatement("select * from studfee"
                + " where " +"status='done' and year = ? ");
        ps2.setString(1,year_txt.getSelectedItem().toString());
        ResultSet rs2 = ps2.executeQuery();
//        in this nested looping we will eliminate all those roll no who have completely submitted 
//        their fee 
/*
eg :  roll no from studdata are 1,2,3,4,5
eg :        roll no    --   1   status -> done
eg :        roll no    --   2   status -> pending
eg :        roll no    --   3   status -> pending
eg :        roll no    --   4   status -> done   ... these records came from studfee
    now adding only 2,3,5 to the combobox as only their fee is pending
*/
        while (rs.next()) {
            String studentRollNo = rs.getString("rollno");
            
//            beforeFirst() is used to reset the cursor to next row 
            rs2.beforeFirst();
            while (rs2.next()) {
if (rs2.getString("rollno").equalsIgnoreCase(studentRollNo) ) {
                    flag = 1;
                    break;
                }
            }
            if(flag ==0){
                roll_txt.addItem(rs.getString("rollno"));
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        roll_lbl = new javax.swing.JLabel();
        course_lbl = new javax.swing.JLabel();
        branch_lbl = new javax.swing.JLabel();
        amt_lbl = new javax.swing.JLabel();
        year_lbl = new javax.swing.JLabel();
        roll_txt = new javax.swing.JComboBox<>();
        name_txt = new javax.swing.JTextField();
        branch_txt = new javax.swing.JTextField();
        course_txt = new javax.swing.JTextField();
        amt_txt = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        year_txt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("STUDENT FEE FORM");

        name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(102, 204, 255));
        name_lbl.setText("NAME");

        roll_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        roll_lbl.setForeground(new java.awt.Color(102, 204, 255));
        roll_lbl.setText("ROLL NO");

        course_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        course_lbl.setForeground(new java.awt.Color(102, 204, 255));
        course_lbl.setText("COURSE");

        branch_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        branch_lbl.setForeground(new java.awt.Color(102, 204, 255));
        branch_lbl.setText("BRANCH");

        amt_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        amt_lbl.setForeground(new java.awt.Color(102, 204, 255));
        amt_lbl.setText("AMOUNT");

        year_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        year_lbl.setForeground(new java.awt.Color(102, 204, 255));
        year_lbl.setText("YEAR");

        roll_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        roll_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll_txtActionPerformed(evt);
            }
        });

        name_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        branch_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        course_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        amt_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        submit_btn.setBackground(new java.awt.Color(102, 153, 255));
        submit_btn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("SUBMIT");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 153, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CANCEL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        year_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "first", "second", "third", "fourth" }));
        year_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        year_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(year_lbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roll_lbl)
                                    .addComponent(name_lbl))
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roll_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(branch_lbl)
                                    .addComponent(course_lbl)
                                    .addComponent(amt_lbl))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amt_txt)
                                    .addComponent(branch_txt)
                                    .addComponent(course_txt))))
                        .addGap(187, 187, 187))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_lbl)
                    .addComponent(year_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roll_lbl)
                    .addComponent(roll_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lbl)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_lbl)
                    .addComponent(course_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branch_lbl)
                    .addComponent(branch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amt_lbl))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roll_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll_txtActionPerformed
        // TODO add your handling code here:
        name_txt.setText("");
        course_txt.setText("");
        branch_txt.setText("");
        amt_txt.setText("");
        try{
            rollno = roll_txt.getSelectedItem().toString();
            Connection con = DBConnect.connect();
//            to fetch details of students
            PreparedStatement ps = con.prepareStatement("select * from student where rollno=?");
            ps.setString(1,rollno);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                name_txt.setText(rs.getString(1));
                course_txt.setText(rs.getString(5));
                branch_txt.setText(rs.getString(12));
            }
            
//            to pending fee of student
            PreparedStatement ps2 = con.prepareStatement("select * from studfee where rollno=? and year=?");
            ps2.setString(1,rollno);
            ps2.setString(2,year_txt.getSelectedItem().toString());
            ResultSet rs2 = ps2.executeQuery();
            while(rs2.next()){
                amt_txt.setText(rs2.getString("fee"));
            }
//            System.out.println("t6.getText()");
//            System.out.println(t6.getText());
             if(amt_txt.getText().equalsIgnoreCase("")){
                                changePendFee =1;
            }
            else{
                                changePendFee =0;
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_roll_txtActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        //       c1.removeAllItems(); 
        try{
            Connection con = DBConnect.connect();
            PreparedStatement p1 = con.prepareStatement("select * from feestruct where course =? and branch = ?");
            p1.setString(1,course_txt.getText());
            p1.setString(2,branch_txt.getText());

            ResultSet rs = p1.executeQuery();
            if(rs.next()){
              totalAmt  = rs.getString(year_txt.getSelectedItem().toString());
            }
            int subAmt = Integer.parseInt(amt_txt.getText());
            int pend = Integer.parseInt(totalAmt)-subAmt;

            if(changePendFee ==1){
                PreparedStatement p2 = con.prepareStatement("insert into studfee values(?,?,?,?)");
               
                
                p2.setString(1,rollno);
                p2.setString(2,String.valueOf(pend));
                p2.setString(4,year_txt.getSelectedItem().toString());
                
                if(subAmt > Integer.parseInt(totalAmt)){
                 JOptionPane.showMessageDialog(null,(-pend)+"full fee submitted successfully and extra amount returned");
                        p2.setString(3,"done");
            }
            else{
                if(pend!=0){
                        JOptionPane.showMessageDialog(null,pend+" amount to be submitted");
                        p2.setString(3,"pending");
                }else{
                        JOptionPane.showMessageDialog(null,"full fee submitted successfully");
                        p2.setString(3,"done");
                }
            }
                System.out.println(p2);
                            p2.executeUpdate();

            }
            else{
                PreparedStatement p2 = con.prepareStatement("update studfee set fee = ? , status = ? where rollno=? ");
       
                p2.setString(1,String.valueOf(pend));
                p2.setString(3,rollno);
                
                 
                if(subAmt > Integer.parseInt(totalAmt)){
                 JOptionPane.showMessageDialog(null,(-pend)+"full fee submitted successfully and extra amount returned");
                        p2.setString(2,"done");
            }
            else{
                if(pend!=0){
                        JOptionPane.showMessageDialog(null,pend+" amount to be submitted");
                        p2.setString(2,"pending");
                }else{
                        JOptionPane.showMessageDialog(null,"full fee submitted successfully");
                        p2.setString(2,"done");
                }
            }
                                System.out.println(p2);
                            p2.executeUpdate();

            } 
            
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_submit_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void year_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_txtActionPerformed
        fetchStud();
    }//GEN-LAST:event_year_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amt_lbl;
    private javax.swing.JTextField amt_txt;
    private javax.swing.JLabel branch_lbl;
    private javax.swing.JTextField branch_txt;
    private javax.swing.JLabel course_lbl;
    private javax.swing.JTextField course_txt;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel roll_lbl;
    private javax.swing.JComboBox<String> roll_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel year_lbl;
    private javax.swing.JComboBox<String> year_txt;
    // End of variables declaration//GEN-END:variables
}
