/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_data;

import com.google.gson.Gson;
import java.sql.*;
//import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
import student_management_system.DBConnect;

/**
 *
 * @author hp
 */
public class stud_data extends javax.swing.JFrame {
    String imgPath;
    ByteArrayOutputStream out = null;
    ImageIcon icon;
    byte[] imageData;
    /**
     * Creates new form stud_data
     */
    public stud_data() {
        initComponents();    
        try{
            Connection con = DBConnect.connect();
            PreparedStatement ps = con.prepareStatement("select max(rollno) from student");
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                String it = rs.getString(1).substring(0,8);
                int rollno = Integer.parseInt(rs.getString(1).substring(8))+1;
                rno_txt.setText(it+rollno);
                rno_txt.setEditable(false);
            }
            else
                System.out.println(false);
        }
        catch (Exception e){}
    }
    public ImageIcon resizePic(String pic){
        ImageIcon myimg = new ImageIcon(pic);
        Image img1 = myimg.getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH);
        return new ImageIcon(img1);
    }
    public void generateQR(){
        Map<String,String> data = new HashMap<>();
        data.put("name",name_txt.getText());
        data.put("email",email_txt.getText());
        data.put("rollno",rno_txt.getText());
        Gson gson = new Gson();
        String jsonData = gson.toJson(data);
        out = QRCode.from(jsonData).withSize(300,250).to(ImageType.PNG).stream();
        try{
            imageData = out.toByteArray();
            icon = new ImageIcon(imageData); 
        }catch(Exception e){}
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rno_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dob_txt = new com.toedter.calendar.JDateChooser();
        cancel_btn = new javax.swing.JButton();
        upload_btn = new javax.swing.JButton();
        rno_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        xii_txt = new javax.swing.JTextField();
        fname_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        x_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        branch_txt = new javax.swing.JComboBox<>();
        course_txt = new javax.swing.JComboBox<>();
        address_txt = new javax.swing.JTextField();
        adhar_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rno_lbl.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        rno_lbl.setForeground(new java.awt.Color(255, 255, 255));
        rno_lbl.setText("ROLL NUMBER");
        jPanel1.add(rno_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, 40));

        name_lbl.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("NAME");
        jPanel1.add(name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 70, 40));

        submit_btn.setBackground(new java.awt.Color(153, 255, 255));
        submit_btn.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        submit_btn.setText("SUBMIT");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        img.setOpaque(true);
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 240));

        email_lbl.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(255, 255, 255));
        email_lbl.setText("EMAIL ID");
        jPanel1.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 200, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADHAR NO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 200, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COURSE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 200, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BRANCH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 220, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADDRESS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 200, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CLASS X (%)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 220, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FATHER'S NAME");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 220, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DATE OF BIRTH");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 220, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PHONE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 220, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CLASS XII (%)");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 200, 40));
        jPanel1.add(dob_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 200, 40));

        cancel_btn.setBackground(new java.awt.Color(153, 255, 255));
        cancel_btn.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        cancel_btn.setText("CANCEL");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, -1));

        upload_btn.setBackground(new java.awt.Color(153, 255, 255));
        upload_btn.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        upload_btn.setText("UPLOAD");
        upload_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btnActionPerformed(evt);
            }
        });
        jPanel1.add(upload_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        rno_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rno_txtActionPerformed(evt);
            }
        });
        jPanel1.add(rno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 200, 40));

        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 40));

        xii_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xii_txtActionPerformed(evt);
            }
        });
        jPanel1.add(xii_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 200, 40));

        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });
        jPanel1.add(fname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 200, 40));

        phone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtActionPerformed(evt);
            }
        });
        jPanel1.add(phone_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 200, 40));

        x_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_txtActionPerformed(evt);
            }
        });
        jPanel1.add(x_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 200, 40));

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 40));

        branch_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "Civil", "Electronics", "IT", "Mechanical" }));
        branch_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_txtActionPerformed(evt);
            }
        });
        jPanel1.add(branch_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 200, -1));

        course_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", "BCA", "BBA", "M.Tech", "MCA", "MBA" }));
        course_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_txtActionPerformed(evt);
            }
        });
        jPanel1.add(course_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 200, -1));
        jPanel1.add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 570, 80));
        jPanel1.add(adhar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 570, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW STUDENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1140, 690));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\CODING\\JAVA\\java projects\\Student_management_system\\images\\download (4).jpeg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DBConnect.connect();
            PreparedStatement a1  = con.prepareStatement("insert into attendence values(?,'-','-')");
            a1.setString(1,rno_txt.getText());
            a1.executeUpdate();
            InputStream ig = new FileInputStream(new File(imgPath));
            generateQR();
            InputStream qr = new ByteArrayInputStream(imageData);
           
            PreparedStatement ps = con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,name_txt.getText()); // name
            ps.setString(2,rno_txt.getText()); // roll no
            ps.setString(3,email_txt.getText()); // email id
            ps.setString(4,xii_txt.getText()); // class xii
            ps.setString(5,course_txt.getSelectedItem().toString()); // course
            ps.setString(6,adhar_txt.getText()); // aadhar
            ps.setString(7,address_txt.getText()); // address
            ps.setString(8,fname_txt.getText()); // father
            ps.setString(9,((JTextField)dob_txt.getDateEditor().getUiComponent()).getText()); // dob
            ps.setString(10,phone_txt.getText()); // phone
            ps.setString(11,x_txt.getText()); // x class
            ps.setString(12,branch_txt.getSelectedItem().toString()); // branch
            ps.setBlob(13,ig); // image 
            ps.setBlob(14,qr); // qr code 
            
            int a = ps.executeUpdate();
            if(a==1){
                JOptionPane.showMessageDialog(null,"Successfully registered a new Student");
                dispose();
            }
            else
               JOptionPane.showMessageDialog(null,"Some Error");

        }catch(Exception e){
            System.out.println(e);
    }//GEN-LAST:event_submit_btnActionPerformed
    }
    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void upload_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btnActionPerformed
        // TODO add your handling code here:
        //to generate pop-up box that will allow to select a file
        JFileChooser file = new JFileChooser();
        //to set the first folder to appear 
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //to select the suitable file type 
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter(".Images","jpg","png","jpeg","gif");
        //to add the suitable file extension to the JFileChooser object named file
        file.addChoosableFileFilter(filefilter);
        //to get thje state if user have selected a file or not
        //if an image is selected then filestate = 1 otherwise filstate = 0 
        int filestate = file.showSaveDialog(null);
        //conditional Statements
        if (filestate == JFileChooser.APPROVE_OPTION){
         //if an image is selected then get the path of folder
            File sf = file.getSelectedFile();
            //get the absolute path i.e starting form the drive eg: C:/Downloads...... the complete path
            String path = sf.getAbsolutePath();
            //send the image/PATH TO RESIZEpIC METHOD TO ADJJUST THE SIZE OF IMAGE SELECTED ACCORDING to the label
            //then set the modified image into label
            img.setIcon(resizePic(path));
            imgPath = path;
        }
        else if(filestate == JFileChooser.CANCEL_OPTION)
            JOptionPane.showConfirmDialog(null,"NO IMAGE SELECTED");    
    }//GEN-LAST:event_upload_btnActionPerformed

    private void rno_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rno_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rno_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void xii_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xii_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xii_txtActionPerformed

    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void phone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_txtActionPerformed

    private void x_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void branch_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branch_txtActionPerformed

    private void course_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stud_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stud_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stud_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stud_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stud_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField adhar_txt;
    private javax.swing.JComboBox<String> branch_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JComboBox<String> course_txt;
    private com.toedter.calendar.JDateChooser dob_txt;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JLabel rno_lbl;
    private javax.swing.JTextField rno_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JButton upload_btn;
    private javax.swing.JTextField x_txt;
    private javax.swing.JTextField xii_txt;
    // End of variables declaration//GEN-END:variables
}
